### ISSUE TITLE
Home page has an overflow on smaller screen sizes

### ISSUE THREAD

**Issue by steph237** [ruqaiyasattar/digitalstethoecopeAI#9]
The overflow on the home page comes up when the scrreen size is around 5.6 inches as shown in the image below. 
![Screenshot_20230313-044503](https://user-images.githubusercontent.com/43364084/224604288-56894eca-18d0-4adb-9a14-a3fda4ff2e68.png)

**Comment by steph237** [comment]
This is the link to a PR that fixes this issue [PR for overflow on small screens](https://github.com/ruqaiyasattar/digitalstethoecopeAI/pull/10)

**Comment by steph237** [comment]
@ruqaiyasattar

**Comment by sonali8434** [comment]
@ruqaiyasattar here is my pull request for the problem #9 https://github.com/ruqaiyasattar/digitalstethoecopeAI/pull/11
